// checksum 0xad2d version 0x90001
/*
  This file was generated by the Qt Quick 2 Application wizard of Qt Creator.
  QtQuick2ControlsApplicationViewer is a convenience class.
  QML paths are handled here.
  It is recommended not to modify this file, since newer versions of Qt Creator
  may offer an updated version of it.

此文件由Qt Creator的Qt Quick 2应用程序向导生成。Qt Quick2ApplicationViewer是一个方便类。
QML路径在此处处理。建议不要修改此文件，因为更新版本的Qt Creator可能会提供更新版本。
*/
#ifndef QTQUICK2APPLICATIONVIEWER_H
#define QTQUICK2APPLICATIONVIEWER_H

#include <QString>

class QtQuick2ControlsApplicationViewer
{
public:
    explicit QtQuick2ControlsApplicationViewer();
    virtual ~QtQuick2ControlsApplicationViewer();

    void setMainQmlFile(const QString &file);
    void addImportPath(const QString &path);
    void show();

private:
    class QtQuick2ApplicationViewerPrivate *d;
};

#endif // QTQUICK2APPLICATIONVIEWER_H
